import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    textAlign: "center",
    backgroundColor: "#FFFFF0",
    padding: 10,
    borderRadius: 25,
    marginHorizontal: 5,
    marginBottom: 5,
    alignItems: "center",
    maxWidth: 120,
    textAlign: "center",
    fontSize: 10,
  },
  cardName: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: "bold",
    maxWidth: "90%",
  },
  modal: {
    flex: 1,
    backgroundColor: "#2B292C",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: 20,
    borderBottomEndRadius: 0,
    borderBottomStartRadius: 0,
  },
  image: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    marginBottom: 10,
  },
  imageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    borderBottomEndRadius: 48,
    borderBottomStartRadius: 48,

    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.39,
    shadowRadius: 8.3,

    elevation: 13,
    width: "100%",
    paddingBottom: 20,
    height: "40%",
  },

  headerModal: {
    marginTop: 20,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  HeaderModalText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },

  title: {
    fontSize: 32,
    marginVertical: 10,
    color: "#fff",
    fontWeight: "bold",
  },
  infoContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    color: "#fff",
  },
  type: {
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 20,
    fontSize: 16,
    color: "#fff",
    textTransform: "uppercase",
    fontWeight: "bold",
    marginVertical: 16,
  },
  info: {
    paddingHorizontal: 30,
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  label: {
    paddingHorizontal: 30,
    fontSize: 8,
    color: "#fff8",
    fontWeight: "bold",
  },

  labelStatus: {
    fontSize: 24,
    marginTop: 32,
    color: "#fff",
    fontWeight: "bold",
  },
  bar: {
    width: "70%",
    backgroundColor: "#fff",
  },
  progreessText: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: "bold",
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 6 },
    position: "absolute",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },

  progressBarContainer: {
    width: "90%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 8,
    textAlign: "left",
  },
  statusBarlabel: {
    fontSize: 9,
    color: "#fff8",
    fontWeight: "bold",
    marginRight: 10,
    width: 32,
  },

  PokeBolaRed: {
    width: 100,
    height: 50,
    backgroundColor: "red",
    borderTopEndRadius: 250,
    borderTopStartRadius: 250,
  },
  PokeBolaWhite: {
    width: 100,
    height: 50,
    backgroundColor: "white",
    borderBottomEndRadius: 250,
    borderBottomStartRadius: 250,
  },
  PokeBolaStrip: {
    zIndex: 10,
    width: "100%",
    height: 10,
    backgroundColor: "#000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  PokeBolaWhiteInner: {
    zIndex: 11,
    width: 25,
    height: 25,
    backgroundColor: "white",
    borderRadius: 250,
    borderColor: "#000",
    borderWidth: 5,
  },

  normal: { backgroundColor: "#A8A77A" },
  fire: { backgroundColor: "#EE8130" },
  water: { backgroundColor: "#6390F0" },
  electric: { backgroundColor: "#F7D02C" },
  grass: { backgroundColor: "#7AC74C" },
  ice: { backgroundColor: "#96D9D6" },
  fighting: { backgroundColor: "#C22E28" },
  poison: { backgroundColor: "#A33EA1" },
  ground: { backgroundColor: "#E2BF65" },
  flying: { backgroundColor: "#A98FF3" },
  psychic: { backgroundColor: "#F95587" },
  bug: { backgroundColor: "#A6B91A" },
  rock: { backgroundColor: "#B6A136" },
  ghost: { backgroundColor: "#735797" },
  dragon: { backgroundColor: "#6F35FC" },
  dark: { backgroundColor: "#705746" },
  steel: { backgroundColor: "#B7B7CE" },
  fairy: { backgroundColor: "#D685AD" },
});
